//! One-role verification and resealing against the committed artifact set.
//!
//! The artifacts come from `crates/router-ab-core/tests/fixtures/tenant-root-recovery`,
//! regenerated by that crate's `tenant_root_recovery_cli_fixtures` test. The
//! recipient key material matches the ceremony fixture's IKM, so these tests
//! exercise the real opening path rather than a stand-in.

use rand_core_09::{CryptoRng, RngCore};
use router_ab_core::{
    TenantRootCustodyLineageId, TenantRootRecoveryRecipientKeypairV1,
    TenantRootRecoveryTrustBundleV1, TenantRootRecoveryTrustEvidenceV1,
    TenantRootRestoreDestinationFingerprintV1, TenantRootRestoreImportKeypairV1,
    TenantRootRestoreSessionIdV1, TwoPartyDeriverRole,
};
use seams_recovery_core::{
    open_and_reseal_role_share_v1, verify_role_package_offline_v1, write_new_file_durably_v1,
    RecoveryKeyFileV1, RestoreDestinationBindingV1,
};
use std::path::{Path, PathBuf};

/// Recipient key material the committed artifact set was sealed to.
const DERIVER_A_KEY_MATERIAL: [u8; 32] = [0xa1; 32];
const DERIVER_B_KEY_MATERIAL: [u8; 32] = [0xb1; 32];

/// An RNG that yields fixed key material first, then a deterministic stream.
///
/// This creates a key file holding the exact recipient key the committed
/// packages were sealed to, without adding a production constructor that
/// accepts caller-chosen private material.
struct ScriptedRng {
    key_material: [u8; 32],
    consumed: bool,
    counter: u8,
}

impl ScriptedRng {
    const fn new(key_material: [u8; 32]) -> Self {
        Self {
            key_material,
            consumed: false,
            counter: 0,
        }
    }
}

impl RngCore for ScriptedRng {
    fn next_u32(&mut self) -> u32 {
        let mut bytes = [0_u8; 4];
        self.fill_bytes(&mut bytes);
        u32::from_le_bytes(bytes)
    }

    fn next_u64(&mut self) -> u64 {
        let mut bytes = [0_u8; 8];
        self.fill_bytes(&mut bytes);
        u64::from_le_bytes(bytes)
    }

    fn fill_bytes(&mut self, destination: &mut [u8]) {
        if !self.consumed && destination.len() == 32 {
            destination.copy_from_slice(&self.key_material);
            self.consumed = true;
            return;
        }
        for byte in destination.iter_mut() {
            self.counter = self.counter.wrapping_add(1);
            *byte = self.counter;
        }
    }
}

impl CryptoRng for ScriptedRng {}

struct Scratch {
    root: PathBuf,
}

impl Scratch {
    fn new(name: &str) -> Self {
        let root = std::env::temp_dir().join(format!("seams-recovery-artifacts-{name}"));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).expect("scratch directory");
        Self { root }
    }

    fn path(&self, name: &str) -> PathBuf {
        self.root.join(name)
    }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.root);
    }
}

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../router-ab-core/tests/fixtures/tenant-root-recovery")
        .join(name)
}

fn trust_bundle() -> TenantRootRecoveryTrustBundleV1 {
    TenantRootRecoveryTrustBundleV1::from_canonical_json(
        &std::fs::read(fixture("trust-bundle.json")).expect("trust bundle"),
    )
    .expect("decode trust bundle")
}

fn key_file(scratch: &Scratch, role: TwoPartyDeriverRole, material: [u8; 32]) -> PathBuf {
    let (file, _) =
        RecoveryKeyFileV1::create(role, &mut ScriptedRng::new(material)).expect("key file");
    let path = scratch.path(&format!("{}.key", role.as_str()));
    write_new_file_durably_v1(&path, &file.to_bytes().expect("bytes")).expect("write key file");
    path
}

fn destination_binding() -> RestoreDestinationBindingV1 {
    let import =
        TenantRootRestoreImportKeypairV1::derive_from_ikm([0x77; 32]).expect("import keypair");
    RestoreDestinationBindingV1 {
        destination_fingerprint: TenantRootRestoreDestinationFingerprintV1::from_bytes([0x66; 32])
            .expect("fingerprint"),
        destination_lineage: TenantRootCustodyLineageId::from_bytes([0x67; 16]).expect("lineage"),
        restore_session_id: TenantRootRestoreSessionIdV1::from_bytes([0x68; 16])
            .expect("session id"),
        import_key_id: "destination-import-key-a-1".to_owned(),
        import_public_key: import.public_key(),
        issued_at_ms: 1_788_000_000_000,
        expires_at_ms: 1_788_000_900_000,
    }
}

#[test]
fn one_role_package_verifies_offline_without_any_recovery_key() {
    let bundle = trust_bundle();
    let report = verify_role_package_offline_v1(
        &fixture("manifest.json"),
        &fixture("deriver-a.backup"),
        TwoPartyDeriverRole::DeriverA,
        &bundle,
        &TenantRootRecoveryTrustEvidenceV1::OfflineRootsOnly,
    )
    .expect("offline verification");

    assert_eq!(report.role, "deriver_a");
    assert_eq!(report.trust_level, "cryptographically_valid_offline");
    assert!(!report.recovery_set_id.is_empty());
    assert_eq!(
        report.recipient_fingerprint_b64u,
        base64_fingerprint(DERIVER_A_KEY_MATERIAL)
    );

    // The other role's file is refused for this role.
    assert!(verify_role_package_offline_v1(
        &fixture("manifest.json"),
        &fixture("deriver-b.backup"),
        TwoPartyDeriverRole::DeriverA,
        &bundle,
        &TenantRootRecoveryTrustEvidenceV1::OfflineRootsOnly,
    )
    .is_err());
}

#[test]
fn opening_and_resealing_needs_the_matching_role_key() {
    let scratch = Scratch::new("reseal");
    let bundle = trust_bundle();
    let binding = destination_binding();
    let key_a = key_file(
        &scratch,
        TwoPartyDeriverRole::DeriverA,
        DERIVER_A_KEY_MATERIAL,
    );

    let resealed = open_and_reseal_role_share_v1(
        &fixture("manifest.json"),
        &fixture("deriver-a.backup"),
        &key_a,
        TwoPartyDeriverRole::DeriverA,
        &bundle,
        &TenantRootRecoveryTrustEvidenceV1::OfflineRootsOnly,
        &binding,
        &mut ScriptedRng::new([0x99; 32]),
    )
    .expect("reseal");

    assert_eq!(resealed.report().role, "deriver_a");
    assert_eq!(&resealed.envelope_bytes()[..8], b"SEAMSRI1");
    // The envelope is ciphertext for the destination, not readable output.
    assert!(!resealed
        .envelope_bytes()
        .windows(8)
        .any(|window| *window == DERIVER_A_KEY_MATERIAL[..8]));

    // Deriver B's key cannot open Deriver A's package.
    let key_b = key_file(
        &scratch,
        TwoPartyDeriverRole::DeriverB,
        DERIVER_B_KEY_MATERIAL,
    );
    assert!(open_and_reseal_role_share_v1(
        &fixture("manifest.json"),
        &fixture("deriver-a.backup"),
        &key_b,
        TwoPartyDeriverRole::DeriverA,
        &bundle,
        &TenantRootRecoveryTrustEvidenceV1::OfflineRootsOnly,
        &destination_binding(),
        &mut ScriptedRng::new([0x99; 32]),
    )
    .is_err());
}

#[test]
fn an_untrusted_bundle_rejects_the_committed_artifacts() {
    let rogue = TenantRootRecoveryTrustBundleV1::new(
        1,
        router_ab_core::TenantRootRecoveryTrustRootV1::new(
            "rogue-root-1",
            ed25519_dalek::SigningKey::from_bytes(&[0xee; 32])
                .verifying_key()
                .to_bytes(),
        )
        .expect("root"),
        Vec::new(),
        Vec::new(),
    )
    .expect("bundle");

    assert!(verify_role_package_offline_v1(
        &fixture("manifest.json"),
        &fixture("deriver-a.backup"),
        TwoPartyDeriverRole::DeriverA,
        &rogue,
        &TenantRootRecoveryTrustEvidenceV1::OfflineRootsOnly,
    )
    .is_err());
}

fn base64_fingerprint(key_material: [u8; 32]) -> String {
    use base64ct::{Base64UrlUnpadded, Encoding};
    let keypair =
        TenantRootRecoveryRecipientKeypairV1::derive_from_ikm(key_material).expect("keypair");
    Base64UrlUnpadded::encode_string(keypair.fingerprint().as_bytes())
}

#[test]
fn proving_recipient_control_needs_the_matching_key_and_challenge() {
    use seams_recovery_core::prove_recovery_recipient_control_v1;

    let scratch = Scratch::new("recipient-proof");
    let key_a = key_file(
        &scratch,
        TwoPartyDeriverRole::DeriverA,
        DERIVER_A_KEY_MATERIAL,
    );
    let challenge = fixture("recipient-challenge-deriver-a.bin");

    let proof =
        prove_recovery_recipient_control_v1(&key_a, TwoPartyDeriverRole::DeriverA, &challenge)
            .expect("proof of control");
    assert_eq!(proof.role, "deriver_a");
    assert_eq!(
        proof.fingerprint_b64u,
        base64_fingerprint(DERIVER_A_KEY_MATERIAL)
    );
    assert!(!proof.confirmation_b64u.is_empty());
    // The result carries public material and a confirmation, never the secret.
    assert_ne!(proof.confirmation_b64u, proof.public_key_b64u);

    // A challenge issued for Deriver A cannot be answered as Deriver B.
    let key_b = key_file(
        &scratch,
        TwoPartyDeriverRole::DeriverB,
        DERIVER_B_KEY_MATERIAL,
    );
    assert!(
        prove_recovery_recipient_control_v1(&key_b, TwoPartyDeriverRole::DeriverB, &challenge,)
            .is_err()
    );

    // The role argument must agree with the key file it names.
    assert!(
        prove_recovery_recipient_control_v1(&key_a, TwoPartyDeriverRole::DeriverB, &challenge,)
            .is_err()
    );
}
