import type {
  AccountSyncSigningSurface,
  EcdsaLoginSessionSurface,
  EcdsaRegistrationSurface,
  WalletCustodyCeremonySurface,
  Ed25519YaoCapabilityActivationSurface,
  EcdsaSessionBootstrapSurface,
  EcdsaSessionControlSurface,
  Ed25519SessionConnectionSurface,
  Ed25519MaterialOwnerQueueSurface,
  EmailOtpRegistrationEnrollmentSurface,
  EmailOtpSigningSessionSurface,
  EvmFamilySigningSurface,
  KeyExportSigningSurface,
  NearSigningSurface,
  NonceCoordinatorSurface,
  PasskeyLoginAssertionSurface,
  RegistrationAccountSurface,
  RegistrationResourceWarmupSurface,
  RpIdSurface,
  RuntimeStartupSurface,
  SeamsWebBaseContext,
  SigningEngineLifecycleEventSurface,
  SignerWorkerContextSurface,
  SigningSessionSurface,
  TempoNonceLifecycleSurface,
  UserProfileStoreSurface,
  WarmSessionStatusSurface,
  WalletIframeWarmupSurface,
  WalletIframeSurfaceMeasurementSurface,
  WalletAuthenticationSurface,
  WalletLockGenerationSurface,
  UnlockedEd25519ExportRootCapabilitySurface,
  WebAuthnRegistrationConfirmationSurface,
  EmailOtpEnrollmentConfirmationSurface,
} from './ports';
import type { UserPreferencesManager } from '@/core/signingEngine/session/userPreferences';
import type { UiConfirmSurfaceMeasurementBinding } from '@/core/signingEngine/uiConfirm/uiConfirm.types';
import type { AppearanceConfig, SeamsConfigsReadonly } from '@/core/types/seams';
import type { WorkerOperationContext } from '@/core/signingEngine/workerManager/executeWorkerOperation';

export type {
  AccountSyncSigningSurface,
  AccountSyncWebContext,
  WalletAuthWebContext,
  DeviceLinkingSigningSurface,
  DeviceLinkingWebContext,
  EcdsaLoginSessionSurface,
  EcdsaRegistrationSurface,
  Ed25519YaoCapabilityActivationSurface,
  EcdsaSessionBootstrapSurface,
  EcdsaSessionControlSurface,
  Ed25519SessionConnectionSurface,
  EmailOtpRegistrationEnrollmentSurface,
  EmailOtpSigningSessionSurface,
  WalletRecoverySigningSurface,
  WalletRecoveryWebContext,
  EvmFamilySigningSurface,
  LocalLoginStateSurface,
  LocalLoginStateWebContext,
  LockSigningSurface,
  LockWebContext,
  LoginUnlockSigningSurface,
  LoginWarmSigningSurface,
  LoginWebContext,
  NearSigningSurface,
  NearSigningWebContext,
  NonceCoordinatorSurface,
  PasskeyLoginAssertionSurface,
  RecentUnlocksSigningSurface,
  RecentUnlocksWebContext,
  RegistrationAccountSurface,
  RegistrationResourceWarmupSurface,
  RegistrationSigningSurface,
  RegistrationWebContext,
  RpIdSurface,
  RuntimeStartupSurface,
  SeamsWebBaseContext,
  SigningEngineLifecycleEventSurface,
  SignerWorkerContextSurface,
  SigningSessionSurface,
  TempoNonceLifecycleSurface,
  TempoSigningSurface,
  UnlockedEd25519ExportRootCapabilitySurface,
  UserAccountLookupSurface,
  UserProfileStoreSurface,
  WalletIframeWarmupSurface,
  WalletAuthenticationSurface,
  WalletSessionReadSurface,
  WalletSessionWebContext,
  WarmSessionStatusSurface,
  WebAuthnRegistrationConfirmationSurface,
} from './ports';

export type * from '../publicApi/types';

export interface SeamsWebSigningSurface
  extends
    RpIdSurface,
    NonceCoordinatorSurface,
    WalletIframeWarmupSurface,
    WalletIframeSurfaceMeasurementSurface,
    WalletAuthenticationSurface,
    WalletLockGenerationSurface,
    RuntimeStartupSurface,
    SigningEngineLifecycleEventSurface,
    WorkerOperationContext,
    SigningSessionSurface,
    Ed25519SessionConnectionSurface,
    EcdsaSessionBootstrapSurface,
    EmailOtpSigningSessionSurface,
    EmailOtpRegistrationEnrollmentSurface,
    EcdsaLoginSessionSurface,
    EcdsaSessionControlSurface,
    SignerWorkerContextSurface,
    WarmSessionStatusSurface,
    NearSigningSurface,
    EvmFamilySigningSurface,
    TempoNonceLifecycleSurface,
    UserProfileStoreSurface,
    RegistrationResourceWarmupSurface,
    RegistrationAccountSurface,
    EcdsaRegistrationSurface,
    Ed25519YaoCapabilityActivationSurface,
    UnlockedEd25519ExportRootCapabilitySurface,
    WalletCustodyCeremonySurface,
    Ed25519MaterialOwnerQueueSurface,
    Pick<AccountSyncSigningSurface, 'storeNearThresholdKeyMaterial'>,
    WebAuthnRegistrationConfirmationSurface,
    EmailOtpEnrollmentConfirmationSurface,
    PasskeyLoginAssertionSurface,
    KeyExportSigningSurface {
  readonly seamsWebConfigs: SeamsConfigsReadonly;
  dispose(): void;
  setAppearance(appearance: AppearanceConfig): void;
  setWalletIframeSurfaceMeasurementBinding(binding: UiConfirmSurfaceMeasurementBinding): void;
  getUserPreferences(): UserPreferencesManager;
}

export type SeamsWebContext = SeamsWebBaseContext<SeamsWebSigningSurface>;
