-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [ed25519_yao_generator]: function definitions
import Aeneas
import Ed25519Yao.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace ed25519_yao_generator

/-- [ed25519_yao_generator::wrapping_add_le_256]: loop body 0:
    Source: 'src/lib.rs', lines 911:4-915:5
    Visibility: public -/
@[rust_loop_body]
def wrapping_add_le_256_loop.body
  (left : Array Std.U8 32#usize) (right : Array Std.U8 32#usize)
  (iter : core.ops.range.Range Std.Usize) (output : Array Std.U8 32#usize)
  (carry : Std.U16) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U8
    32#usize) × Std.U16) (Array Std.U8 32#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done output)
  | some index =>
    let i ← Array.index_usize left index
    let i1 ← lift (core.convert.num.FromU16U8.from i)
    let i2 ← Array.index_usize right index
    let i3 ← lift (core.convert.num.FromU16U8.from i2)
    let i4 ← i1 + i3
    let sum ← i4 + carry
    let i5 ← lift (UScalar.cast .U8 sum)
    let a ← Array.update output index i5
    let carry1 ← sum >>> 8#i32
    ok (cont (iter1, a, carry1))

/-- [ed25519_yao_generator::wrapping_add_le_256]: loop 0:
    Source: 'src/lib.rs', lines 911:4-915:5
    Visibility: public -/
@[rust_loop]
def wrapping_add_le_256_loop
  (iter : core.ops.range.Range Std.Usize) (left : Array Std.U8 32#usize)
  (right : Array Std.U8 32#usize) (output : Array Std.U8 32#usize)
  (carry : Std.U16) :
  Result (Array Std.U8 32#usize)
  := do
  loop
    (fun (iter1, output1, carry1) => wrapping_add_le_256_loop.body left right
      iter1 output1 carry1)
    (iter, output, carry)

/-- [ed25519_yao_generator::wrapping_add_le_256]:
    Source: 'src/lib.rs', lines 907:0-918:1
    Visibility: public -/
def wrapping_add_le_256
  (left : Array Std.U8 32#usize) (right : Array Std.U8 32#usize) :
  Result (Array Std.U8 32#usize)
  := do
  let output := Array.repeat 32#usize 0#u8
  wrapping_add_le_256_loop { start := 0#usize, «end» := 32#usize } left right
    output 0#u16

/-- [ed25519_yao_generator::clamp_rfc8032]:
    Source: 'src/lib.rs', lines 921:0-926:1
    Visibility: public -/
def clamp_rfc8032
  (digest_prefix : Array Std.U8 32#usize) :
  Result (Array Std.U8 32#usize)
  := do
  let i ← Array.index_usize digest_prefix 0#usize
  let i1 ← lift (i &&& 248#u8)
  let digest_prefix1 ← Array.update digest_prefix 0#usize i1
  let i2 ← Array.index_usize digest_prefix1 31#usize
  let i3 ← lift (i2 &&& 63#u8)
  let digest_prefix2 ← Array.update digest_prefix1 31#usize i3
  let i4 ← Array.index_usize digest_prefix2 31#usize
  let i5 ← lift (i4 ||| 64#u8)
  Array.update digest_prefix2 31#usize i5

end ed25519_yao_generator
