-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [ed25519_yao_generator]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace ed25519_yao_generator

end ed25519_yao_generator
