#![cfg(all(feature = "ecdsa-role-local-client", feature = "typescript-bindings"))]

use std::{env, fs, path::PathBuf};

use signer_core::commands::{
    Base64UrlEncodingV1, EcdsaBootstrapSecretSourceV1,
    EcdsaClientBootstrapAlgorithmV1, EcdsaClientBootstrapContextV1, EcdsaClientBootstrapFactsV1,
    EcdsaClientBootstrapParticipantsV1, EcdsaPreparePublicFactsV1, EcdsaReadyPublicFactsV1,
    EcdsaRoleLocalPendingStateBlobV1,
    EcdsaRoleLocalReadyStateBlobV1, FinalizeEcdsaClientBootstrapCommandKindV1,
    FinalizeEcdsaClientBootstrapCommandV1, FinalizeEcdsaClientBootstrapErrorCodeV1,
    FinalizeEcdsaClientBootstrapOutputV1, PendingStateBlobKindV1,
    PrepareEcdsaClientBootstrapCommandKindV1, PrepareEcdsaClientBootstrapCommandV1,
    PrepareEcdsaClientBootstrapErrorCodeV1, PrepareEcdsaClientBootstrapOutputV1,
    ReadyStateBlobKindV1, RelayerPublicIdentityV1, Secp256k1CurveNameV1, SignerCommandVersion,
    SignerCoreProducerV1,
};
use ts_rs::{Config, TS};

const UPDATE_ENV: &str = "UPDATE_SIGNER_CORE_TYPES";
const GENERATED_HEADER: &str = concat!(
    "// This file was generated by `pnpm generate:signer-core-types`.\n",
    "// Do not edit this file manually.\n\n",
);

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|path| path.parent())
        .expect("signer-core crate is under crates/signer-core")
        .to_path_buf()
}

fn generated_schema_path() -> PathBuf {
    repo_root().join("packages/wallet/src/core/platform/generated/signerCoreCommands.ts")
}

fn push_decl<T: TS + 'static>(out: &mut String, cfg: &Config) {
    out.push_str("export ");
    out.push_str(&T::decl(cfg));
    out.push_str("\n\n");
}

fn generated_signer_core_commands_ts() -> String {
    let cfg = Config::new();
    let mut out = String::from(GENERATED_HEADER);

    push_decl::<SignerCommandVersion>(&mut out, &cfg);
    push_decl::<EcdsaBootstrapSecretSourceV1>(&mut out, &cfg);
    push_decl::<EcdsaClientBootstrapAlgorithmV1>(&mut out, &cfg);
    push_decl::<EcdsaClientBootstrapContextV1>(&mut out, &cfg);
    push_decl::<EcdsaClientBootstrapParticipantsV1>(&mut out, &cfg);
    push_decl::<PrepareEcdsaClientBootstrapCommandKindV1>(&mut out, &cfg);
    push_decl::<PrepareEcdsaClientBootstrapCommandV1>(&mut out, &cfg);
    push_decl::<PendingStateBlobKindV1>(&mut out, &cfg);
    push_decl::<ReadyStateBlobKindV1>(&mut out, &cfg);
    push_decl::<Secp256k1CurveNameV1>(&mut out, &cfg);
    push_decl::<Base64UrlEncodingV1>(&mut out, &cfg);
    push_decl::<SignerCoreProducerV1>(&mut out, &cfg);
    push_decl::<EcdsaRoleLocalPendingStateBlobV1>(&mut out, &cfg);
    push_decl::<EcdsaRoleLocalReadyStateBlobV1>(&mut out, &cfg);
    push_decl::<EcdsaClientBootstrapFactsV1>(&mut out, &cfg);
    push_decl::<EcdsaPreparePublicFactsV1>(&mut out, &cfg);
    push_decl::<PrepareEcdsaClientBootstrapOutputV1>(&mut out, &cfg);
    push_decl::<PrepareEcdsaClientBootstrapErrorCodeV1>(&mut out, &cfg);
    push_decl::<RelayerPublicIdentityV1>(&mut out, &cfg);
    push_decl::<FinalizeEcdsaClientBootstrapCommandKindV1>(&mut out, &cfg);
    push_decl::<FinalizeEcdsaClientBootstrapCommandV1>(&mut out, &cfg);
    push_decl::<EcdsaReadyPublicFactsV1>(&mut out, &cfg);
    push_decl::<FinalizeEcdsaClientBootstrapOutputV1>(&mut out, &cfg);
    push_decl::<FinalizeEcdsaClientBootstrapErrorCodeV1>(&mut out, &cfg);
    out.pop();
    out
}

#[test]
fn signer_core_typescript_schemas_are_current() {
    let generated = generated_signer_core_commands_ts();
    let path = generated_schema_path();

    if env::var(UPDATE_ENV).as_deref() == Ok("1") {
        fs::create_dir_all(path.parent().expect("generated file has parent directory"))
            .expect("create generated schema directory");
        fs::write(&path, generated).expect("write generated schema file");
        return;
    }

    let existing = fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!(
            "failed to read generated signer-core schema file at {}: {error}",
            path.display()
        )
    });

    assert_eq!(
        existing, generated,
        "generated signer-core schemas are stale; run `pnpm generate:signer-core-types`"
    );
}
