#![cfg(feature = "typescript-bindings")]

use std::{env, fs, path::PathBuf};

use router_ab_core::{
    Ed25519YaoCeremonyBindingV1, Ed25519YaoCeremonyIdentityV1, Ed25519YaoCircuitFamilyV1,
    Ed25519YaoCircuitIdV1, Ed25519YaoInputPairBindingV1, Ed25519YaoOperationV1,
    Ed25519YaoProtocolIdV1, ExpensiveWorkKindV1, LifecycleScopeV1, MpcMaterialActivationRefKindV1,
    MpcMaterialActivationRefV1, PublicDigest32, RequestKind, RootShareEpoch,
    RouterRequestPolicyClaimsV1,
};
use ts_rs::{Config, TS};

const UPDATE_ENV: &str = "UPDATE_ROUTER_AB_ED25519_YAO_TYPES";
const GENERATED_HEADER: &str = concat!(
    "// This file was generated by `pnpm generate:router-ab-ed25519-yao-types`.\n",
    "// Do not edit this file manually.\n\n",
    "export type RouterAbEd25519YaoBytes32V1 = readonly number[];\n\n",
    "export type RouterAbEd25519YaoSessionIdV1 = RouterAbEd25519YaoBytes32V1;\n\n",
    "export type RouterAbEd25519YaoStableKeyContextBindingV1 = RouterAbEd25519YaoBytes32V1;\n\n",
);

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|path| path.parent())
        .expect("router-ab-core crate is under crates/router-ab-core")
        .to_path_buf()
}

fn generated_schema_path() -> PathBuf {
    repo_root().join("packages/shared-ts/src/utils/generated/routerAbEd25519YaoCore.ts")
}

fn push_decl<T: TS + 'static>(out: &mut String, cfg: &Config) {
    out.push_str("export ");
    let declaration = T::decl(cfg);
    for (index, line) in declaration.lines().enumerate() {
        if index > 0 {
            out.push('\n');
        }
        out.push_str(line.trim_end());
    }
    out.push_str("\n\n");
}

fn generated_router_ab_ed25519_yao_types_ts() -> String {
    let cfg = Config::new().with_array_tuple_limit(0);
    let mut out = String::from(GENERATED_HEADER);
    push_decl::<RootShareEpoch>(&mut out, &cfg);
    push_decl::<RequestKind>(&mut out, &cfg);
    push_decl::<ExpensiveWorkKindV1>(&mut out, &cfg);
    push_decl::<RouterRequestPolicyClaimsV1>(&mut out, &cfg);
    push_decl::<LifecycleScopeV1>(&mut out, &cfg);
    push_decl::<MpcMaterialActivationRefKindV1>(&mut out, &cfg);
    push_decl::<MpcMaterialActivationRefV1>(&mut out, &cfg);
    push_decl::<Ed25519YaoCircuitFamilyV1>(&mut out, &cfg);
    push_decl::<Ed25519YaoOperationV1>(&mut out, &cfg);
    push_decl::<Ed25519YaoCeremonyBindingV1>(&mut out, &cfg);
    push_decl::<Ed25519YaoCircuitIdV1>(&mut out, &cfg);
    push_decl::<Ed25519YaoProtocolIdV1>(&mut out, &cfg);
    push_decl::<Ed25519YaoCeremonyIdentityV1>(&mut out, &cfg);
    push_decl::<PublicDigest32>(&mut out, &cfg);
    push_decl::<Ed25519YaoInputPairBindingV1>(&mut out, &cfg);
    out.pop();
    out
}

#[test]
fn router_ab_ed25519_yao_typescript_bindings_are_current() {
    let generated = generated_router_ab_ed25519_yao_types_ts();
    let path = generated_schema_path();

    if env::var(UPDATE_ENV).as_deref() == Ok("1") {
        fs::create_dir_all(path.parent().expect("generated file has parent directory"))
            .expect("create generated schema directory");
        fs::write(&path, generated).expect("write generated schema file");
        return;
    }

    let existing = fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!(
            "failed to read generated router-ab-ed25519-yao schema file at {}: {error}",
            path.display()
        )
    });
    assert_eq!(
        existing, generated,
        "generated Router A/B Ed25519 Yao schemas are stale; run `pnpm generate:router-ab-ed25519-yao-types`"
    );
}
