-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [router_ab_ecdsa_derivation]: function definitions
import Aeneas
import RouterAbEcdsaDerivation.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace router_ab_ecdsa_derivation

/-- [router_ab_ecdsa_derivation::wire::{router_ab_ecdsa_derivation::wire::ServerEvalOperation}::allowed_output_kind]:
    Source: 'src/lib.rs', lines 28:8-37:9
    Visibility: public -/
def wire.ServerEvalOperation.allowed_output_kind
  (self : wire.ServerEvalOperation) : Result wire.AllowedOutputKind := do
  match self with
  | wire.ServerEvalOperation.RegistrationBootstrap =>
    ok wire.AllowedOutputKind.ThresholdMaterialOnly
  | wire.ServerEvalOperation.SessionBootstrap =>
    ok wire.AllowedOutputKind.ThresholdMaterialOnly
  | wire.ServerEvalOperation.NonExportSign =>
    ok wire.AllowedOutputKind.ThresholdMaterialOnly
  | wire.ServerEvalOperation.ExplicitKeyExport =>
    ok wire.AllowedOutputKind.ThresholdMaterialAndRelayerExportShare

/-- [router_ab_ecdsa_derivation::server::boundary::operation_boundary_from_operation]:
    Source: 'src/lib.rs', lines 267:8-274:9
    Visibility: public -/
def server.boundary.operation_boundary_from_operation
  (operation : wire.ServerEvalOperation) :
  Result server.boundary.VisibleOperationBoundary
  := do
  let aok ← wire.ServerEvalOperation.allowed_output_kind operation
  ok { operation, allowed_output_kind := aok }

/-- [router_ab_ecdsa_derivation::server::boundary::non_export_boundary_from_output]:
    Source: 'src/lib.rs', lines 276:8-287:9
    Visibility: public -/
def server.boundary.non_export_boundary_from_output
  (output : client.NonExportClientOutput) :
  Result server.boundary.VisibleNonExportBoundary
  := do
  ok
    {
      derivation_client_share_public_key33 :=
        output.derivation_client_share_public_key33,
      relayer_public_key33 := output.relayer_public_key33,
      threshold_public_key33 := output.threshold_public_key33,
      threshold_ethereum_address20 := output.threshold_ethereum_address20,
      client_share_retry_counter := output.client_share_retry_counter,
      relayer_share_retry_counter := output.relayer_share_retry_counter
    }

/-- [router_ab_ecdsa_derivation::server::boundary::explicit_export_boundary_from_output]:
    Source: 'src/lib.rs', lines 289:8-301:9
    Visibility: public -/
def server.boundary.explicit_export_boundary_from_output
  (output : client.ExplicitExportClientOutput) :
  Result server.boundary.VisibleExplicitExportBoundary
  := do
  ok
    {
      relayer_export_share32 := output.relayer_export_share32,
      derivation_client_share_public_key33 :=
        output.derivation_client_share_public_key33,
      relayer_public_key33 := output.relayer_public_key33,
      threshold_public_key33 := output.threshold_public_key33,
      threshold_ethereum_address20 := output.threshold_ethereum_address20,
      client_share_retry_counter := output.client_share_retry_counter,
      relayer_share_retry_counter := output.relayer_share_retry_counter
    }

/-- [router_ab_ecdsa_derivation::server::boundary::visible_client_boundary_from_output]:
    Source: 'src/lib.rs', lines 303:8-312:9
    Visibility: public -/
def server.boundary.visible_client_boundary_from_output
  (output : client.ClientOutput) :
  Result server.boundary.VisibleClientBoundary
  := do
  match output with
  | client.ClientOutput.NonExport output1 =>
    let vneb ← server.boundary.non_export_boundary_from_output output1
    ok (server.boundary.VisibleClientBoundary.NonExport vneb)
  | client.ClientOutput.ExplicitExport output1 =>
    let veeb ← server.boundary.explicit_export_boundary_from_output output1
    ok (server.boundary.VisibleClientBoundary.ExplicitExport veeb)

/-- [router_ab_ecdsa_derivation::server::boundary::visible_finalize_boundary_from_envelope]:
    Source: 'src/lib.rs', lines 314:8-329:9
    Visibility: public -/
def server.boundary.visible_finalize_boundary_from_envelope
  (finalize : wire.FinalizeEnvelope) :
  Result server.boundary.VisibleFinalizeBoundary
  := do
  ok
    {
      operation := finalize.operation,
      raw_root_material_dropped := finalize.raw_root_material_dropped,
      relayer_key_id := finalize.relayer_key_id,
      context_binding32 := finalize.context_binding32,
      derivation_client_share_public_key33 :=
        finalize.derivation_client_share_public_key33,
      relayer_public_key33 := finalize.relayer_public_key33,
      threshold_public_key33 := finalize.threshold_public_key33,
      threshold_ethereum_address20 := finalize.threshold_ethereum_address20,
      client_share_retry_counter := finalize.client_share_retry_counter,
      relayer_share_retry_counter := finalize.relayer_share_retry_counter
    }

/-- [router_ab_ecdsa_derivation::server::boundary::visible_boundary_from_respond_response]:
    Source: 'src/lib.rs', lines 347:8-355:9
    Visibility: public -/
def server.boundary.visible_boundary_from_respond_response
  (response : server.RespondResponse) :
  Result server.boundary.VisibleRespondBoundary
  := do
  let vob ←
    server.boundary.operation_boundary_from_operation
      response.finalize.operation
  let vcb ←
    server.boundary.visible_client_boundary_from_output response.client_output
  let vfb ←
    server.boundary.visible_finalize_boundary_from_envelope response.finalize
  ok { operation := vob, client_output := vcb, finalize := vfb }

/-- [router_ab_ecdsa_derivation::server::boundary::hidden_eval_input_boundary_from_staged_request]:
    Source: 'src/lib.rs', lines 357:8-371:9
    Visibility: public -/
def server.boundary.hidden_eval_input_boundary_from_staged_request
  (staged : server.StagedServerSession)
  (request : wire.ThresholdRespondRequest) :
  Result server.boundary.HiddenEvalInputBoundary
  := do
  let aok ←
    wire.ServerEvalOperation.allowed_output_kind staged.prepare.operation
  ok
    {
      operation := staged.prepare.operation,
      allowed_output_kind := aok,
      context := staged.prepare.context,
      relayer_key_id := staged.prepare.relayer_key_id,
      derivation_client_share_public_key33 :=
        request.derivation_client_share_public_key33,
      client_share_retry_counter := request.client_share_retry_counter,
      expected_relayer_key_id := request.expected_relayer_key_id,
      y_relayer32_le := staged.y_relayer32_le
    }

/-- [router_ab_ecdsa_derivation::server::boundary::hidden_eval_transport_boundary_from_respond_response]:
    Source: 'src/lib.rs', lines 373:8-382:9
    Visibility: public -/
def server.boundary.hidden_eval_transport_boundary_from_respond_response
  (response : server.RespondResponse) :
  Result server.boundary.HiddenEvalTransportBoundary
  := do
  let visible ←
    server.boundary.visible_boundary_from_respond_response response
  ok
    {
      operation := visible.operation,
      client_output := visible.client_output,
      finalize := visible.finalize
    }

/-- [router_ab_ecdsa_derivation::server::boundary::hidden_eval_persisted_state_boundary_from_finalized_session]:
    Source: 'src/lib.rs', lines 384:8-399:9
    Visibility: public -/
def server.boundary.hidden_eval_persisted_state_boundary_from_finalized_session
  (session : server.FinalizedServerSession) :
  Result server.boundary.HiddenEvalPersistedStateBoundary
  := do
  ok
    {
      operation := session.operation,
      raw_root_material_dropped := session.retained.raw_root_material_dropped,
      relayer_key_id := session.retained.relayer_key_id,
      relayer_share32 := session.retained.relayer_share32,
      derivation_client_share_public_key33 :=
        session.retained.derivation_client_share_public_key33,
      relayer_public_key33 := session.retained.relayer_public_key33,
      threshold_public_key33 := session.retained.threshold_public_key33,
      threshold_ethereum_address20 :=
        session.retained.threshold_ethereum_address20,
      client_share_retry_counter := session.retained.client_share_retry_counter,
      relayer_share_retry_counter :=
        session.retained.relayer_share_retry_counter
    }

/-- [router_ab_ecdsa_derivation::server::boundary::hidden_eval_boundary_from_parts]:
    Source: 'src/lib.rs', lines 401:8-411:9
    Visibility: public -/
def server.boundary.hidden_eval_boundary_from_parts
  (input : server.boundary.HiddenEvalInputBoundary)
  (transport : server.boundary.HiddenEvalTransportBoundary)
  (persisted : server.boundary.HiddenEvalPersistedStateBoundary) :
  Result server.boundary.HiddenEvalBoundary
  := do
  ok { input, transport, persisted }

end router_ab_ecdsa_derivation
