-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [router_ab_ecdsa_derivation]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace router_ab_ecdsa_derivation

/-- [router_ab_ecdsa_derivation::shared::context::RouterAbEcdsaDerivationStableKeyContext]
    Source: 'src/lib.rs', lines 4:8-6:9
    Visibility: public -/
structure shared.context.RouterAbEcdsaDerivationStableKeyContext where
  application_binding_digest : Array Std.U8 32#usize

/-- [router_ab_ecdsa_derivation::wire::ServerEvalOperation]
    Source: 'src/lib.rs', lines 14:4-19:5
    Visibility: public -/
@[discriminant isize]
inductive wire.ServerEvalOperation where
| RegistrationBootstrap : wire.ServerEvalOperation
| SessionBootstrap : wire.ServerEvalOperation
| NonExportSign : wire.ServerEvalOperation
| ExplicitKeyExport : wire.ServerEvalOperation

/-- [router_ab_ecdsa_derivation::wire::AllowedOutputKind]
    Source: 'src/lib.rs', lines 22:4-25:5
    Visibility: public -/
@[discriminant isize]
inductive wire.AllowedOutputKind where
| ThresholdMaterialOnly : wire.AllowedOutputKind
| ThresholdMaterialAndRelayerExportShare : wire.AllowedOutputKind

/-- [router_ab_ecdsa_derivation::wire::PrepareEnvelope]
    Source: 'src/lib.rs', lines 41:4-45:5
    Visibility: public -/
structure wire.PrepareEnvelope where
  operation : wire.ServerEvalOperation
  context : shared.context.RouterAbEcdsaDerivationStableKeyContext
  relayer_key_id : String

/-- [router_ab_ecdsa_derivation::wire::ThresholdRespondRequest]
    Source: 'src/lib.rs', lines 48:4-52:5
    Visibility: public -/
structure wire.ThresholdRespondRequest where
  derivation_client_share_public_key33 : Array Std.U8 33#usize
  client_share_retry_counter : Std.U32
  expected_relayer_key_id : String

/-- [router_ab_ecdsa_derivation::wire::FinalizeEnvelope]
    Source: 'src/lib.rs', lines 55:4-66:5
    Visibility: public -/
structure wire.FinalizeEnvelope where
  operation : wire.ServerEvalOperation
  raw_root_material_dropped : Bool
  relayer_key_id : String
  context_binding32 : Array Std.U8 32#usize
  derivation_client_share_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [router_ab_ecdsa_derivation::client::NonExportClientOutput]
    Source: 'src/lib.rs', lines 73:4-80:5
    Visibility: public -/
structure client.NonExportClientOutput where
  derivation_client_share_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [router_ab_ecdsa_derivation::client::ExplicitExportClientOutput]
    Source: 'src/lib.rs', lines 83:4-91:5
    Visibility: public -/
structure client.ExplicitExportClientOutput where
  relayer_export_share32 : Array Std.U8 32#usize
  derivation_client_share_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [router_ab_ecdsa_derivation::client::ClientOutput]
    Source: 'src/lib.rs', lines 94:4-97:5
    Visibility: public -/
@[discriminant isize]
inductive client.ClientOutput where
| NonExport : client.NonExportClientOutput → client.ClientOutput
| ExplicitExport : client.ExplicitExportClientOutput → client.ClientOutput

/-- [router_ab_ecdsa_derivation::server::RetainedServerState]
    Source: 'src/lib.rs', lines 120:4-130:5
    Visibility: public -/
structure server.RetainedServerState where
  raw_root_material_dropped : Bool
  relayer_key_id : String
  relayer_share32 : Array Std.U8 32#usize
  derivation_client_share_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [router_ab_ecdsa_derivation::server::FinalizedServerSession]
    Source: 'src/lib.rs', lines 133:4-137:5
    Visibility: public -/
structure server.FinalizedServerSession where
  operation : wire.ServerEvalOperation
  context : shared.context.RouterAbEcdsaDerivationStableKeyContext
  retained : server.RetainedServerState

/-- [router_ab_ecdsa_derivation::server::StagedServerSession]
    Source: 'src/lib.rs', lines 140:4-143:5
    Visibility: public -/
structure server.StagedServerSession where
  prepare : wire.PrepareEnvelope
  y_relayer32_le : Array Std.U8 32#usize

/-- [router_ab_ecdsa_derivation::server::RespondResponse]
    Source: 'src/lib.rs', lines 146:4-149:5
    Visibility: public -/
structure server.RespondResponse where
  client_output : client.ClientOutput
  finalize : wire.FinalizeEnvelope

/-- [router_ab_ecdsa_derivation::server::boundary::VisibleOperationBoundary]
    Source: 'src/lib.rs', lines 161:8-164:9
    Visibility: public -/
structure server.boundary.VisibleOperationBoundary where
  operation : wire.ServerEvalOperation
  allowed_output_kind : wire.AllowedOutputKind

/-- [router_ab_ecdsa_derivation::server::boundary::VisibleNonExportBoundary]
    Source: 'src/lib.rs', lines 167:8-174:9
    Visibility: public -/
structure server.boundary.VisibleNonExportBoundary where
  derivation_client_share_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [router_ab_ecdsa_derivation::server::boundary::VisibleExplicitExportBoundary]
    Source: 'src/lib.rs', lines 177:8-185:9
    Visibility: public -/
structure server.boundary.VisibleExplicitExportBoundary where
  relayer_export_share32 : Array Std.U8 32#usize
  derivation_client_share_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [router_ab_ecdsa_derivation::server::boundary::VisibleClientBoundary]
    Source: 'src/lib.rs', lines 188:8-191:9
    Visibility: public -/
@[discriminant isize]
inductive server.boundary.VisibleClientBoundary where
| NonExport :
  server.boundary.VisibleNonExportBoundary →
  server.boundary.VisibleClientBoundary
| ExplicitExport :
  server.boundary.VisibleExplicitExportBoundary →
  server.boundary.VisibleClientBoundary

/-- [router_ab_ecdsa_derivation::server::boundary::VisibleFinalizeBoundary]
    Source: 'src/lib.rs', lines 194:8-205:9
    Visibility: public -/
structure server.boundary.VisibleFinalizeBoundary where
  operation : wire.ServerEvalOperation
  raw_root_material_dropped : Bool
  relayer_key_id : String
  context_binding32 : Array Std.U8 32#usize
  derivation_client_share_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [router_ab_ecdsa_derivation::server::boundary::VisibleRespondBoundary]
    Source: 'src/lib.rs', lines 221:8-225:9
    Visibility: public -/
structure server.boundary.VisibleRespondBoundary where
  operation : server.boundary.VisibleOperationBoundary
  client_output : server.boundary.VisibleClientBoundary
  finalize : server.boundary.VisibleFinalizeBoundary

/-- [router_ab_ecdsa_derivation::server::boundary::HiddenEvalInputBoundary]
    Source: 'src/lib.rs', lines 228:8-237:9
    Visibility: public -/
structure server.boundary.HiddenEvalInputBoundary where
  operation : wire.ServerEvalOperation
  allowed_output_kind : wire.AllowedOutputKind
  context : shared.context.RouterAbEcdsaDerivationStableKeyContext
  relayer_key_id : String
  derivation_client_share_public_key33 : Array Std.U8 33#usize
  client_share_retry_counter : Std.U32
  expected_relayer_key_id : String
  y_relayer32_le : Array Std.U8 32#usize

/-- [router_ab_ecdsa_derivation::server::boundary::HiddenEvalTransportBoundary]
    Source: 'src/lib.rs', lines 240:8-244:9
    Visibility: public -/
structure server.boundary.HiddenEvalTransportBoundary where
  operation : server.boundary.VisibleOperationBoundary
  client_output : server.boundary.VisibleClientBoundary
  finalize : server.boundary.VisibleFinalizeBoundary

/-- [router_ab_ecdsa_derivation::server::boundary::HiddenEvalPersistedStateBoundary]
    Source: 'src/lib.rs', lines 247:8-258:9
    Visibility: public -/
structure server.boundary.HiddenEvalPersistedStateBoundary where
  operation : wire.ServerEvalOperation
  raw_root_material_dropped : Bool
  relayer_key_id : String
  relayer_share32 : Array Std.U8 32#usize
  derivation_client_share_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [router_ab_ecdsa_derivation::server::boundary::HiddenEvalBoundary]
    Source: 'src/lib.rs', lines 261:8-265:9
    Visibility: public -/
structure server.boundary.HiddenEvalBoundary where
  input : server.boundary.HiddenEvalInputBoundary
  transport : server.boundary.HiddenEvalTransportBoundary
  persisted : server.boundary.HiddenEvalPersistedStateBoundary

end router_ab_ecdsa_derivation
